Algoritmo "semnome"
// Disciplina  :  [Linguagem e Lógica de Programação]
// Professor   : Antonio Carlos Nicolodi
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Davy
// Data atual  : 19/09/2023

Var
// Seção de Declarações das variáveis 
 n: inteiro

Inicio
// Seção de Comandos, procedimento, funções, operadores, etc... 
para n de 100 ate 200 faca
se (n % 2 = 0) entao
escreval(n)
fimse
fimpara

Fimalgoritmo